from random import Random

import frappe
from frappe.utils import add_days, add_months, getdate


CUSTOMERS = [
    ("GI-1001", "Northstar Labs", "North China", "Beijing", "SaaS", "Partner", "Enterprise"),
    ("GI-1002", "Riverlane Retail", "East China", "Shanghai", "E-commerce", "Paid Search", "Mid-Market"),
    ("GI-1003", "Bright Class", "South China", "Shenzhen", "Education", "Referral", "SMB"),
    ("GI-1004", "Pulse Pay", "APAC", "Singapore", "FinTech", "Event", "Enterprise"),
    ("GI-1005", "ForgeWorks", "East China", "Suzhou", "Manufacturing", "Outbound", "Mid-Market"),
    ("GI-1006", "Medica Cloud", "North America", "San Francisco", "Healthcare", "Organic", "Enterprise"),
    ("GI-1007", "Atlas Freight", "Europe", "Berlin", "Logistics", "Partner", "Business"),
    ("GI-1008", "CreatorHub", "South China", "Guangzhou", "Media", "Marketplace", "Growth"),
    ("GI-1009", "Finch Analytics", "West China", "Chengdu", "SaaS", "Referral", "Growth"),
    ("GI-1010", "Urban Basket", "North China", "Tianjin", "E-commerce", "Paid Search", "Starter"),
    ("GI-1011", "Campus One", "East China", "Hangzhou", "Education", "Organic", "Growth"),
    ("GI-1012", "BlueMint Health", "APAC", "Tokyo", "Healthcare", "Partner", "Business"),
    ("GI-1013", "Stackpilot", "North America", "Austin", "SaaS", "Outbound", "Enterprise"),
    ("GI-1014", "MetroParts", "Europe", "Paris", "Manufacturing", "Event", "Business"),
    ("GI-1015", "ShipZen", "South China", "Hong Kong", "Logistics", "Marketplace", "Growth"),
    ("GI-1016", "MediaSpring", "East China", "Nanjing", "Media", "Organic", "Starter"),
    ("GI-1017", "Oak Ledger", "North China", "Beijing", "FinTech", "Referral", "Business"),
    ("GI-1018", "CloudCrafters", "APAC", "Seoul", "SaaS", "Paid Search", "Mid-Market"),
    ("GI-1019", "LearnLoop", "West China", "Chongqing", "Education", "Partner", "SMB"),
    ("GI-1020", "GreenCart", "Europe", "Amsterdam", "E-commerce", "Organic", "Growth"),
    ("GI-1021", "MediOrbit", "North America", "Boston", "Healthcare", "Outbound", "Enterprise"),
    ("GI-1022", "CargoVista", "APAC", "Sydney", "Logistics", "Event", "Business"),
    ("GI-1023", "StudioGrid", "South China", "Shenzhen", "Media", "Referral", "Starter"),
    ("GI-1024", "SignalWorks", "East China", "Shanghai", "SaaS", "Marketplace", "Mid-Market"),
]


PLAN_MRR = {
    "Starter": 199,
    "Growth": 699,
    "Business": 1800,
    "Enterprise": 5200,
    "Free": 0,
}


def after_install():
    seed_mock_data()


def seed_mock_data():
    if frappe.db.exists("Customer Lifecycle Event", {"customer_id": ["like", "GI-%"]}):
        return

    rng = Random(42)
    base_date = getdate("2025-07-01")
    churn_reasons = ["Price", "Missing Feature", "Low Usage", "Competitor", "Payment Failed"]

    for index, customer in enumerate(CUSTOMERS):
        customer_id, customer_name, region, city, industry, channel, plan = customer
        start_date = add_days(add_months(base_date, index % 10), rng.randint(0, 21))
        segment = _segment_for_plan(plan)
        base_mrr = PLAN_MRR.get(plan, 499)
        seats = max(3, int(base_mrr / 180) + rng.randint(1, 18))

        _insert_event(
            customer_id=customer_id,
            customer_name=customer_name,
            event_type="Signup",
            event_date=start_date,
            customer_segment=segment,
            plan=plan,
            mrr=base_mrr,
            seats=seats,
            region=region,
            city=city,
            industry=industry,
            channel=channel,
            health_score=rng.randint(64, 92),
            notes="Mock signup generated by Growth Insights.",
        )

        if index % 3 != 0:
            _insert_event(
                customer_id=customer_id,
                customer_name=customer_name,
                event_type="Activation",
                event_date=add_days(start_date, rng.randint(7, 25)),
                customer_segment=segment,
                plan=plan,
                mrr=base_mrr,
                seats=seats,
                region=region,
                city=city,
                industry=industry,
                channel=channel,
                health_score=rng.randint(72, 96),
                notes="First value milestone reached.",
            )

        if index % 4 == 1:
            expansion_mrr = int(base_mrr * rng.choice([0.25, 0.35, 0.5]))
            _insert_event(
                customer_id=customer_id,
                customer_name=customer_name,
                event_type="Expansion",
                event_date=add_days(add_months(start_date, rng.randint(2, 5)), rng.randint(0, 12)),
                customer_segment=segment,
                plan=plan,
                mrr=expansion_mrr,
                seats=max(1, int(seats * 0.35)),
                region=region,
                city=city,
                industry=industry,
                channel=channel,
                health_score=rng.randint(78, 98),
                notes="Seat or module expansion.",
            )

        if index in {4, 9, 13, 18, 22}:
            _insert_event(
                customer_id=customer_id,
                customer_name=customer_name,
                event_type="Churn",
                event_date=add_days(add_months(start_date, rng.randint(3, 8)), rng.randint(4, 24)),
                customer_segment=segment,
                plan=plan,
                mrr=base_mrr,
                seats=seats,
                region=region,
                city=city,
                industry=industry,
                channel=channel,
                health_score=rng.randint(18, 44),
                churn_reason=rng.choice(churn_reasons),
                notes="Mock churn event for demo reporting.",
            )

        if index in {9, 18}:
            _insert_event(
                customer_id=customer_id,
                customer_name=customer_name,
                event_type="Reactivation",
                event_date=add_days(add_months(start_date, 10), rng.randint(1, 18)),
                customer_segment=segment,
                plan=plan,
                mrr=base_mrr,
                seats=seats,
                region=region,
                city=city,
                industry=industry,
                channel=channel,
                health_score=rng.randint(70, 88),
                notes="Recovered through win-back campaign.",
            )

    frappe.db.commit()


def _segment_for_plan(plan):
    if plan == "Enterprise":
        return "Enterprise"
    if plan == "Business":
        return "Mid-Market"
    if plan == "Growth":
        return "SMB"
    return "Startup"


def _insert_event(**values):
    doc = frappe.new_doc("Customer Lifecycle Event")
    doc.update(values)
    doc.insert(ignore_permissions=True)
